using MailKit.Net.Smtp;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MimeKit;
using MimeKit.Text;
using MailKit.Security;

namespace SocialNetwork.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class MailController : ControllerBase
    {
        [HttpPost]
        public IActionResult SendEmail(string body)
        {
            var email = new MimeMessage();
            email.From.Add(MailboxAddress.Parse("savagebtvv@gmail.com"));
            email.To.Add(MailboxAddress.Parse("stavgladiator@gmail.com"));
            email.Subject = "This message is automatically generated by .net web api application.";
            email.Body = new TextPart(TextFormat.Plain) { Text = body };


            using var smtp = new SmtpClient();
            smtp.Connect("smtp.gmail.com", 587, SecureSocketOptions.StartTls);
            smtp.Authenticate("savagebtvv@gmail.com", "hoyz vzuk bjkq beaz");
            smtp.Send(email);
            smtp.Disconnect(true);
            return Ok();
        }
    }
}
